#include "MultiGraph.h"
#include "Exceptions.h"
#include "IntPair.h"
#include <iostream>
#include <iomanip>
#include <fstream>

//=======================//
// Implemented Functions //
//=======================//
MultiGraph::MultiGraph()
{}

MultiGraph::MultiGraph(const std::string& filePath)
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this function !   //
    // ============================= //
    // Tokens
    std::string tokens[5];
    std::ifstream mapFile(filePath.c_str());

    if(!mapFile.is_open())
    {
        std::cout << "Unable to open " << filePath << std::endl;
        return;
    }

    // Read line by line
    std::string line;
    while (std::getline(mapFile, line))
    {
        // Empty Line Skip
        if(line.empty()) continue;
        // Comment Skip
        if(line[0] == '#') continue;

        // Tokenize the line
        int i = 0;
        std::istringstream stream(line);
        while(stream >> tokens[i]) i++;

        // Single token (Meaning it is a vertex)
        if(i == 1)
        {
            InsertVertex(tokens[0]);
        }
        // Exactly 5 tokens (Meaning it is an edge)
        else if(i == 5)
        {
            // Rename vars for readablity
            const std::string& vertexFromName = tokens[0];
            const std::string& vertexToName = tokens[1];
            const std::string& edgeName = tokens[2];
            float weight0 = static_cast<float>(std::atof(tokens[3].c_str()));
            float weight1 = static_cast<float>(std::atof(tokens[4].c_str()));
            AddEdge(edgeName, vertexFromName, vertexToName,
                    weight0, weight1);
        }
        else std::cerr << "Token Size Mismatch" << std::endl;
    }
}

void MultiGraph::PrintPath(const std::vector<int>& orderedVertexEdgeIndexList,
                           float heuristicWeight,
                           bool sameLine) const
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this file !       //
    // ============================= //

    // Name is too long
    const std::vector<int>& ove = orderedVertexEdgeIndexList;
    // Invalid list
    // At least three items should be available
    if(ove.size() < 3) return;

    // Check vertex and an edge
    for(size_t i = 0; i < orderedVertexEdgeIndexList.size(); i += 2)
    {
        int vertexId = ove[i];
        if(vertexId >= static_cast<int>(vertexList.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "VertexId " << vertexId
                      << " not found!" << std::endl;
            return;
        }


        const GraphVertex& vertex = vertexList[vertexId];
        std::cout << vertex.name;
        if(!sameLine) std::cout << "\n";
        // Only find and print the weight if next is available
        if(i == ove.size() - 1) break;
        int nextVertexId = ove[i + 2];
        if(nextVertexId >= static_cast<int>(vertexList.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "VertexId " << vertexId
                    << " not found!" << std::endl;
            return;
        }

        // Find the edge between these two vertices
        int localEdgeId = ove[i + 1];
        if(localEdgeId >= static_cast<int>(vertex.edges.size()))
        {
            // Return if there is a bad vertex id
            std::cout << "EdgeId " << localEdgeId
                      << " not found in " << vertexId << "!" << std::endl;
            return;
        }

        const GraphEdge& edge = vertex.edges[localEdgeId];

        // Combine with heuristic (linear interpolation)
        float weight = Lerp(edge.weight[0], edge.weight[1],
                            heuristicWeight);

        std::cout << "-" << std::setfill('-')
                  << std::setw(4)
                  << weight << "->";
    }
    // Print endline on the last vertex if same line is set
    if(sameLine) std::cout << "\n";
    // Reset fill value because it "sticks" to the std out
    std::cout << std::setfill(' ');
    std::cout.flush();
}

void MultiGraph::PrintEntireGraph() const
{
    // ============================= //
    // This function is implemented  //
    // Do not edit this function !   //
    // ============================= //
    for(size_t i = 0; i < vertexList.size(); i++)
    {
        const GraphVertex& v = vertexList[i];
        std::cout << v.name << "\n";
        for(size_t j = 0; j < v.edges.size(); j++)
        {
            const GraphEdge& edge = v.edges[j];

            // List the all vertex names and weight
            std::cout << "    -"
                      << std::setfill('-')
                      << std::setw(4) << edge.weight[0]
                      << "-"
                      << std::setw(4) << edge.weight[1]
                      << "-> ";
            std::cout << vertexList[edge.endVertexIndex].name;
            std::cout << " (" << edge.name << ")" << "\n";
        }
    }
    // Reset fill value because it "sticks" to the std out
    std::cout << std::setfill(' ');
    std::cout.flush();
}



bool MultiGraph::search_vertex(const std::string& vertexname) const{
    int vertexnumber=vertexList.size();
    for(int j=0;j<vertexnumber;j++){
        if(vertexList[j].name==vertexname){
            return true;
        }
    }
    return false;
}
int MultiGraph::search_vertex_index(const std::string& vertexname) const{
    int vertexnumber=vertexList.size();
    for(int j=0;j<vertexnumber;j++){
        if(vertexList[j].name==vertexname){
            return j;
        }
    }
    
}

bool MultiGraph::search_edge(const std::string& vertexname,const std::string& edgename,int& endVertexIndex,const std::string& prevertexname) const{
    int vertexnumber=vertexList.size();
    int i=0;
    for(;i<vertexnumber;i++){
        if(vertexList[i].name==vertexname){
            break;
        }
        
    }
    int edgesnumber=vertexList[i].edges.size();
    for(int j=0;j<edgesnumber;j++){
        if(vertexList[i].edges[j].name==edgename){
            endVertexIndex=vertexList[i].edges[j].endVertexIndex;
            if(vertexList[endVertexIndex].name==prevertexname){
                continue;
            }
            return true;
        }
    }
    return false;
    
    
}
bool MultiGraph::search_edge_v2(const std::string& vertexfromname,const std::string& vertextoname,const std::string& edgename,int& edgeindex) const{
    int vertexnumber=vertexList.size();
    int i=0;
    for(;i<vertexnumber;i++){
        if(vertexList[i].name==vertexfromname){
            break;
        }
        
    }
    int edgesnumber=vertexList[i].edges.size();
    int myedgeindex=0;
    for(;myedgeindex<edgesnumber;edgeindex++){
        if(vertexList[i].edges[myedgeindex].name==edgename && vertexList[vertexList[i].edges[myedgeindex].endVertexIndex].name==vertextoname){
            edgeindex=myedgeindex;
            return true;
        }
    }
    return false;
    
    
}

std::vector <GraphVertex> MultiGraph::get_vertexlist() const{
    return vertexList;
    
}

bool MultiGraph::filtered_helper(const std::vector<std::string>& edgeNames,int myvertind,int edgeindex) const{
    for(int i=0;i<edgeNames.size();i++){
        if(edgeNames[i]==vertexList[myvertind].edges[edgeindex].name){
            return true;
        }
    }
    return false;
}




float MultiGraph::Lerp(float w0, float w1, float alpha)
{
   float lerpvalue;
   lerpvalue=(w0*(1-alpha))+(w1*(alpha));
    return lerpvalue;
}

void MultiGraph::InsertVertex(const std::string& vertexName)
{
    int vertexnumber= vertexList.size();
    for(int i=0;i<vertexnumber;i++){
        if(vertexList[i].name==vertexName){
            throw DuplicateVertexException(vertexName);
        }
    }
    GraphVertex newvertex;
    newvertex.name=vertexName;
    vertexList.push_back(newvertex);
    
}

void MultiGraph::RemoveVertex(const std::string& vertexName)
{
    int vertexnumber=vertexList.size();
    for(int i=0;i<vertexnumber;i++){
        if(vertexList[i].name==vertexName){
            vertexList[i].edges.clear();
            vertexList.erase(vertexList.begin()+i);
            return;
        }
    }
    throw VertexNotFoundException(vertexName);
}

void MultiGraph::AddEdge(const std::string& edgeName,
                         const std::string& vertexFromName,
                         const std::string& vertexToName,
                         float weight0, float weight1)
{
    int vertexnumber=vertexList.size();
    int j=0;
    for(;j<vertexnumber;j++){
        if(vertexList[j].name==vertexToName){
            break;
        }
        else if(j==(vertexnumber-1)){
            throw VertexNotFoundException(vertexToName);
        }
    }
    
    for(int i=0;i<vertexnumber;i++){
        if(vertexList[i].name==vertexFromName){
            int edgenumber=vertexList[i].edges.size();
            for(int k=0;k<edgenumber;k++){
                if(vertexList[i].edges[k].name==edgeName & vertexList[i].edges[k].endVertexIndex==j){
                    throw SameNamedEdgeException(edgeName,vertexFromName,vertexToName);
                }
            }
            GraphEdge newedge;
            newedge.name=edgeName;
            newedge.weight[0]=weight0;
            newedge.weight[1]=weight1;
            newedge.endVertexIndex=j;
            vertexList[i].edges.push_back(newedge);
            return;
        }
    }
    throw VertexNotFoundException(vertexFromName);


    
}

void MultiGraph::RemoveEdge(const std::string& edgeName,
                            const std::string& vertexFromName,
                            const std::string& vertexToName)
{
    int vertexnumber=vertexList.size();
    int j=0;
    for(;j<vertexnumber;j++){
        if(vertexList[j].name==vertexToName){
            break;
        }
        else if(j==(vertexnumber-1)){
            throw VertexNotFoundException(vertexToName);
        }
    }
    
    for(int i=0;i<vertexnumber;i++){
        if(vertexList[i].name==vertexFromName){
            int edgenumber=vertexList[i].edges.size();
            for(int k=0;k<edgenumber;k++){
                if(vertexList[i].edges[k].name==edgeName & vertexList[i].edges[k].endVertexIndex==j){
                    vertexList[i].edges.erase(vertexList[i].edges.begin()+k);
                    return;
                }
            }
            throw EdgeNotFoundException(vertexFromName,edgeName);
            
        }
    }
    throw VertexNotFoundException(vertexFromName);
}

bool MultiGraph::HeuristicShortestPath(std::vector<int>& orderedVertexEdgeIndexList,
                                       const std::string& vertexNameFrom,
                                       const std::string& vertexNameTo,
                                       float heuristicWeight) const
{
    if(!search_vertex(vertexNameFrom) ){
        throw VertexNotFoundException(vertexNameFrom);
    }
    if(!search_vertex(vertexNameTo)){
        throw VertexNotFoundException(vertexNameTo);
    }
    int vertexnumber=vertexList.size();
    orderedVertexEdgeIndexList.clear();

    std::vector<float> distance(vertexnumber,INFINITY);
    std::vector<Pair<int,int>> previouspair(vertexnumber,{-1,-1});
    int startindex=search_vertex_index(vertexNameFrom);
    int realendindex=search_vertex_index(vertexNameTo);

    MinPairHeap<int,int> mypqvert;
    MinPairHeap<int,int> mypqedge;
    Pair<int,int> mypairvert;
    Pair<int,int> mypairedge;
    distance[startindex]=0;

    for(int i=0;i<vertexnumber;i++){
        mypairvert.key=distance[i];
        mypairvert.value=i;
        mypqvert.push(mypairvert);
    }
    
    while(!mypqvert.empty()){
        int mydistance=mypqvert.top().key;
        int myvertind=mypqvert.top().value;
        mypqvert.pop();
        float weightvalue;
        int new_dist;
        for(int edgeind=0;edgeind<vertexList[myvertind].edges.size();edgeind++){
            weightvalue=Lerp(vertexList[myvertind].edges[edgeind].weight[0],vertexList[myvertind].edges[edgeind].weight[1],heuristicWeight);
            new_dist=distance[myvertind]+weightvalue;
            int endvertindex=vertexList[myvertind].edges[edgeind].endVertexIndex;
            if(new_dist<distance[endvertindex]){
                distance[endvertindex]=new_dist;
                Pair<int,int> prevpair;
                prevpair.key=myvertind; //where previous come from
                prevpair.value=edgeind; //which edge(as index) it uses to come from 
                previouspair[endvertindex]=prevpair;
                while(!mypqvert.empty()){ //for decrease priority???? hepsini çıkar başka pqya ekle .eklerken değişikliği yap.
                    Pair<int,int> mypairedge;
                    
                    mypairedge.key=mypqvert.top().key;
                    mypairedge.value=mypqvert.top().value;
                    if(mypairedge.value==endvertindex){
                        mypairedge.key=new_dist;
                    }
                    mypqvert.pop();
                    mypqedge.push(mypairedge);
                    
                    
                }
                while(!mypqedge.empty()){//hepsini tekrar asıl pqya ekle
                    Pair<int,int> mypairvert;
                    
                    mypairvert.key=mypqedge.top().key;
                    mypairvert.value=mypqedge.top().value;

                    mypqedge.pop();
                    mypqvert.push(mypairvert);
                    
                    
                }
                
                    
            }//END OF IF
            
        }//END OF FOR
        
    }//END OF WHILE
    
    
    int my_vertex=realendindex;
    while(my_vertex!=-1 && previouspair[my_vertex].key!=-1){
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), my_vertex);
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), previouspair[my_vertex].value); // Insert edge index
        my_vertex=previouspair[my_vertex].key;
    }
    if(my_vertex==startindex){
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(),my_vertex);
        return true;

    }

    
    
    orderedVertexEdgeIndexList.clear();
    return false;
}

bool MultiGraph::FilteredShortestPath(std::vector<int>& orderedVertexEdgeIndexList,
                                      const std::string& vertexNameFrom,
                                      const std::string& vertexNameTo,
                                      float heuristicWeight,
                                      const std::vector<std::string>& edgeNames) const
{
    if(!search_vertex(vertexNameFrom) ){
        throw VertexNotFoundException(vertexNameFrom);
    }
    if(!search_vertex(vertexNameTo)){
        throw VertexNotFoundException(vertexNameTo);
    }
    int vertexnumber=vertexList.size();
    orderedVertexEdgeIndexList.clear();

    std::vector<float> distance(vertexnumber,INFINITY);
    std::vector<Pair<int,int>> previouspair(vertexnumber,{-1,-1});
    int startindex=search_vertex_index(vertexNameFrom);
    int realendindex=search_vertex_index(vertexNameTo);

    MinPairHeap<int,int> mypqvert;
    MinPairHeap<int,int> mypqedge;
    Pair<int,int> mypairvert;
    Pair<int,int> mypairedge;
    distance[startindex]=0;

    for(int i=0;i<vertexnumber;i++){
        mypairvert.key=distance[i];
        mypairvert.value=i;
        mypqvert.push(mypairvert);
    }
    
    while(!mypqvert.empty()){
        int mydistance=mypqvert.top().key;
        int myvertind=mypqvert.top().value;
        mypqvert.pop();
        float weightvalue;
        int new_dist;
        for(int edgeind=0;edgeind<vertexList[myvertind].edges.size();edgeind++){
            if(filtered_helper(edgeNames,myvertind,edgeind)){
                continue;
            }
            weightvalue=Lerp(vertexList[myvertind].edges[edgeind].weight[0],vertexList[myvertind].edges[edgeind].weight[1],heuristicWeight);
            new_dist=distance[myvertind]+weightvalue;
            int endvertindex=vertexList[myvertind].edges[edgeind].endVertexIndex;
            if(new_dist<distance[endvertindex]){
                distance[endvertindex]=new_dist;
                Pair<int,int> prevpair;
                prevpair.key=myvertind; //where previous come from
                prevpair.value=edgeind; //which edge(as index) it uses to come from 
                previouspair[endvertindex]=prevpair;
                while(!mypqvert.empty()){ //for decrease priority???? hepsini çıkar başka pqya ekle .eklerken değişikliği yap.
                    Pair<int,int> mypairedge;
                    
                    mypairedge.key=mypqvert.top().key;
                    mypairedge.value=mypqvert.top().value;
                    if(mypairedge.value==endvertindex){
                        mypairedge.key=new_dist;
                    }
                    mypqvert.pop();
                    mypqedge.push(mypairedge);
                    
                    
                }
                while(!mypqedge.empty()){//hepsini tekrar asıl pqya ekle
                    Pair<int,int> mypairvert;
                    
                    mypairvert.key=mypqedge.top().key;
                    mypairvert.value=mypqedge.top().value;

                    mypqedge.pop();
                    mypqvert.push(mypairvert);
                    
                    
                }
                
                    
            }//END OF IF
            
        }//END OF FOR
        
    }//END OF WHILE
    
    
    int my_vertex=realendindex;
    while(my_vertex!=-1 && previouspair[my_vertex].key!=-1){
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), my_vertex);
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(), previouspair[my_vertex].value); // Insert edge index
        my_vertex=previouspair[my_vertex].key;
    }
    if(my_vertex==startindex){
        orderedVertexEdgeIndexList.insert(orderedVertexEdgeIndexList.begin(),my_vertex);
        return true;

    }

    
    
    orderedVertexEdgeIndexList.clear();
    return false;
}

int MultiGraph::BiDirectionalEdgeCount() const
{
    int vertexnumber=vertexList.size();
    int count=0;
    for(int i=0;i<vertexnumber;i++){
        int edgenumber=vertexList[i].edges.size();
        for(int j=0;j<edgenumber;j++){
            std::string check =vertexList[i].edges[j].name;
            int checkindex=vertexList[i].edges[j].endVertexIndex;
            int checksize=vertexList[checkindex].edges.size();
            for(int k=0;k<checksize;k++){
                if(vertexList[checkindex].edges[k].endVertexIndex==i && vertexList[checkindex].edges[k].name==check){
                    count++;
                }
            }
        }
    }
    return count/2;
}

int MultiGraph::MaxDepthViaEdgeName(const std::string& vertexName,
                                    const std::string& edgeName) const
{

    if(!search_vertex(vertexName)){
        throw VertexNotFoundException(vertexName);
    }
    int depth=0;
    int endv=0;
    int vertexnumber=vertexList.size();
    int startindex=search_vertex_index(vertexName);

    MinPairHeap<int,int>mypq;
    std::vector<int> depthvector(vertexnumber,-1);
    Pair<int,int> mypair;
    mypair.key=0;
    mypair.value=startindex;
    depthvector[startindex]=0;
    mypq.push(mypair);
    
    while(!mypq.empty()){
        int currentdepth=mypq.top().key;
        int currentindex=mypq.top().value;
        mypq.pop();
        for(int i=0;i<vertexList[currentindex].edges.size();i++){
            if(vertexList[currentindex].edges[i].name==edgeName){
                int endvertindex=vertexList[currentindex].edges[i].endVertexIndex;
                int newdepth =currentdepth+1;
                if( depthvector[endvertindex]==-1){
                    depthvector[endvertindex]=newdepth;
                    Pair<int,int> mynewpair;
                    mynewpair.key=newdepth;
                    mynewpair.value=endvertindex;
                    mypq.push(mynewpair);       
                }
            }
        }  
    }    
    int find_maxdepth=0;
    for(int i=0;i<vertexnumber;i++){
        if(depthvector[i]>find_maxdepth){
            find_maxdepth=depthvector[i];
        }
    }
    return find_maxdepth;
    
    
}